<?php

namespace App\Http\Requests\Guest\Cadastro\Capitular;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Str;


class CreateRequest extends FormRequest
{

    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'paise_EN' => 'required',
            'nome_EN' => 'required|max:500',
            'celular_EN' => 'required|max:500',
            'data_nascimento_EN' => 'required|max:500',
            'profissao_EN' => 'required|max:500',
            'idioma_EN' => 'required|max:500',
            'data_casamento_EN' => 'required|max:500',
            'filho_EN' => 'required|max:500',
            'endereco_EN' => 'required|max:500',
            'email_EN' => 'required|max:500',
            'path_familia_01_EN' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
            'path_familia_02_EN' => 'image|mimes:jpeg,png,jpg,gif,svg|max:1024',
            'path_familia_03_EN' => 'image|mimes:jpeg,png,jpg,gif,svg|max:1024',
            'data_uniao_familia_EN' => 'required|max:500',
            'curso_EN' => 'required|max:500',
            'ideal_curso_EN' => 'required|max:500',
            'ano_consagracao_EN' => 'required|max:300',
            'santuario_EN' => 'required|max:500',
            'apostolado_EN' => 'required|max:500',
            'desejo_casal_EN' => 'required',
            'palavra_EN' => 'required|max:500',
            'frase_EN' => 'required|max:500',
            'expectativa_EN' => 'required|max:500',
            'paise_DE' => 'required',
            'nome_DE' => 'required|max:500',
            'celular_DE' => 'required|max:500',
            'data_nascimento_DE' => 'required|max:500',
            'profissao_DE' => 'required|max:500',
            'idioma_DE' => 'required|max:500',
            'data_casamento_DE' => 'required|max:500',
            'filho_DE' => 'required|max:500',
            'endereco_DE' => 'required|max:500',
            'email_DE' => 'required|max:500',
            'data_uniao_familia_DE' => 'required|max:500',
            'curso_DE' => 'required|max:500',
            'ideal_curso_DE' => 'required|max:500',
            'ano_consagracao_DE' => 'required|max:300',
            'santuario_DE' => 'required|max:500',
            'apostolado_DE' => 'required|max:500',
            'desejo_casal_DE' => 'required',
            'palavra_DE' => 'required|max:500',
            'frase_DE' => 'required|max:500',
            'expectativa_DE' => 'required|max:500',
            'paise_ES' => 'required',
            'nome_ES' => 'required|max:500',
            'celular_ES' => 'required|max:500',
            'data_nascimento_ES' => 'required|max:500',
            'profissao_ES' => 'required|max:500',
            'idioma_ES' => 'required|max:500',
            'data_casamento_ES' => 'required|max:500',
            'filho_ES' => 'required|max:500',
            'endereco_ES' => 'required|max:500',
            'email_ES' => 'required|max:500',
            'data_uniao_familia_ES' => 'required|max:500',
            'curso_ES' => 'required|max:500',
            'ideal_curso_ES' => 'required|max:500',
            'ano_consagracao_ES' => 'required|max:300',
            'santuario_ES' => 'required|max:500',
            'apostolado_ES' => 'required|max:500',
            'desejo_casal_ES' => 'required',
            'palavra_ES' => 'required|max:500',
            'frase_ES' => 'required|max:500',
            'expectativa_ES' => 'required|max:500',
        ];
    }

    public function messages()
    {
        return [
            'paise_EN.required' => 'Country (EN) required',
            'nome_EN.required' => 'Name (EN) required',
            'nome_EN.max' => 'Name (EN) max: 500',
            'celular_EN.required' => 'Cell Phone (EN) required',
            'celular_EN.max' => 'Cell Phone (EN) max: 500',
            'data_nascimento_EN.required' => 'Birth Date (EN) required',
            'data_nascimento_EN.max' => 'Birth Date (EN) max: 500',
            'profissao_EN.required' => 'Profession (EN) required',
            'profissao_EN.max' => 'Profession (EN) max: 500',
            'idioma_EN.required' => 'Language (EN) required',
            'idioma_EN.max' => 'Language (EN) max: 500',
            'data_casamento_EN.required' => 'Wedding Date (EN) required',
            'data_casamento_EN.max' => 'Wedding Date (EN) max: 500',
            'filho_EN.required' => 'Son (EN) required',
            'filho_EN.max' => 'Son (EN) max: 500',
            'endereco_EN.required' => 'Address (EN) required',
            'endereco_EN.max' => 'Address (EN) max: 500',
            'email_EN.required' => 'E-mail (EN) required',
            'email_EN.max' => 'E-mail (EN) max: 500',
            'path_familia_01_EN.required' => 'Image 01 (EN) required',
            'path_familia_01_EN.image' => 'Image 01 (EN) only type image',
            'path_familia_01_EN.mimes' => 'Image 01 (EN) only JPEG|JPG|PNG|GIF|SVG',
            'path_familia_01_EN.max' => 'Image 01 (EN) max: 1Mb.',
            'path_familia_02_EN.image' => 'Image 02 (EN) only type image',
            'path_familia_02_EN.mimes' => 'Image 02 (EN) only JPEG|JPG|PNG|GIF|SVG',
            'path_familia_02_EN.max' => 'Image 02 (EN) max: 1Mb.',
            'path_familia_03_EN.image' => 'Image 03 (EN) only type image',
            'path_familia_03_EN.mimes' => 'Image 03 (EN) only JPEG|JPG|PNG|GIF|SVG',
            'path_familia_03_EN.max' => 'Image 03 (EN) max: 1Mb.',
            'data_uniao_familia_EN.required' => 'Family Uion Date (EN) required',
            'data_uniao_familia_EN.max' => 'Family Uion Date (EN) max: 500',
            'curso_EN.required' => 'Course (EN) required',
            'curso_EN.max' => 'Course (EN) max: 500',
            'ideal_curso_EN.required' => 'Course Ideal (EN) required',
            'ideal_curso_EN.max' => 'Course Ideal (EN) max: 500',
            'ano_consagracao_EN.required' => 'Year of Consecration (EN) required',
            'ano_consagracao_EN.max' => 'Year of Consecration (EN) max: 500',
            'santuario_EN.required' => 'Sanctuary (EN) required',
            'santuario_EN.max' => 'Sanctuary (EN) max: 500',
            'apostolado_EN.required' => 'Apostolate (EN) required',
            'apostolado_EN.max' => 'Apostolate (EN) max: 500',
            'desejo_casal_EN.required' => 'Desire Couple (EN) required',
            'palavra_EN.required' => 'Word (EN) required',
            'palavra_EN.max' => 'Word (EN) max: 500',
            'frase_EN.required' => 'Phrase (EN) required',
            'frase_EN.max' => 'Phrase (EN) max: 500',
            'expectativa_EN.required' => 'Expectation (EN) required',
            'expectativa_EN.max' => 'Expectation (EN) max: 500',
            'paise_DE.required' => 'Country (DE) required',
            'nome_DE.required' => 'Name (DE) required',
            'nome_DE.max' => 'Name (DE) max: 500',
            'celular_DE.required' => 'Cell Phone (DE) required',
            'celular_DE.max' => 'Cell Phone (DE) max: 500',
            'data_nascimento_DE.required' => 'Birth Date (DE) required',
            'data_nascimento_DE.max' => 'Birth Date (DE) max: 500',
            'profissao_DE.required' => 'Profession (DE) required',
            'profissao_DE.max' => 'Profession (DE) max: 500',
            'idioma_DE.required' => 'Language (DE) required',
            'idioma_DE.max' => 'Language (DE) max: 500',
            'data_casamento_DE.required' => 'Wedding Date (DE) required',
            'data_casamento_DE.max' => 'Wedding Date (DE) max: 500',
            'filho_DE.required' => 'Son (DE) required',
            'filho_DE.max' => 'Son (DE) max: 500',
            'endereco_DE.required' => 'Address (DE) required',
            'endereco_DE.max' => 'Address (DE) max: 500',
            'email_DE.required' => 'E-mail (DE) required',
            'email_DE.max' => 'E-mail (DE) max: 500',
            'data_uniao_familia_DE.required' => 'Family Uion Date (DE) required',
            'data_uniao_familia_DE.max' => 'Family Uion Date (DE) max: 500',
            'curso_DE.required' => 'Course (DE) required',
            'curso_DE.max' => 'Course (DE) max: 500',
            'ideal_curso_DE.required' => 'Course Ideal (DE) required',
            'ideal_curso_DE.max' => 'Course Ideal (DE) max: 500',
            'ano_consagracao_DE.required' => 'Year of Consecration (DE) required',
            'ano_consagracao_DE.max' => 'Year of Consecration (DE) max: 500',
            'santuario_DE.required' => 'Sanctuary (DE) required',
            'santuario_DE.max' => 'Sanctuary (DE) max: 500',
            'apostolado_DE.required' => 'Apostolate (DE) required',
            'apostolado_DE.max' => 'Apostolate (DE) max: 500',
            'desejo_casal_DE.required' => 'Desire Couple (DE) required',
            'palavra_DE.required' => 'Word (DE) required',
            'palavra_DE.max' => 'Word (DE) max: 500',
            'frase_DE.required' => 'Phrase (DE) required',
            'frase_DE.max' => 'Phrase (DE) max: 500',
            'expectativa_DE.required' => 'Expectation (DE) required',
            'expectativa_DE.max' => 'Expectation (DE) max: 500',
            'paise_ES.required' => 'Country (ES) required',
            'nome_ES.required' => 'Name (ES) required',
            'nome_ES.max' => 'Name (ES) max: 500',
            'celular_ES.required' => 'Cell Phone (ES) required',
            'celular_ES.max' => 'Cell Phone (ES) max: 500',
            'data_nascimento_ES.required' => 'Birth Date (ES) required',
            'data_nascimento_ES.max' => 'Birth Date (ES) max: 500',
            'profissao_ES.required' => 'Profession (ES) required',
            'profissao_ES.max' => 'Profession (ES) max: 500',
            'idioma_ES.required' => 'Language (ES) required',
            'idioma_ES.max' => 'Language (ES) max: 500',
            'data_casamento_ES.required' => 'Wedding Date (ES) required',
            'data_casamento_ES.max' => 'Wedding Date (ES) max: 500',
            'filho_ES.required' => 'Son (ES) required',
            'filho_ES.max' => 'Son (ES) max: 500',
            'endereco_ES.required' => 'Address (ES) required',
            'endereco_ES.max' => 'Address (ES) max: 500',
            'email_ES.required' => 'E-mail (ES) required',
            'email_ES.max' => 'E-mail (ES) max: 500',
            'data_uniao_familia_ES.required' => 'Family Uion Date (ES) required',
            'data_uniao_familia_ES.max' => 'Family Uion Date (ES) max: 500',
            'curso_ES.required' => 'Course (ES) required',
            'curso_ES.max' => 'Course (ES) max: 500',
            'ideal_curso_ES.required' => 'Course Ideal (ES) required',
            'ideal_curso_ES.max' => 'Course Ideal (ES) max: 500',
            'ano_consagracao_ES.required' => 'Year of Consecration (ES) required',
            'ano_consagracao_ES.max' => 'Year of Consecration (ES) max: 500',
            'santuario_ES.required' => 'Sanctuary (ES) required',
            'santuario_ES.max' => 'Sanctuary (ES) max: 500',
            'apostolado_ES.required' => 'Apostolate (ES) required',
            'apostolado_ES.max' => 'Apostolate (ES) max: 500',
            'desejo_casal_ES.required' => 'Desire Couple (ES) required',
            'palavra_ES.required' => 'Word (ES) required',
            'palavra_ES.max' => 'Word (ES) max: 500',
            'frase_ES.required' => 'Phrase (ES) required',
            'frase_ES.max' => 'Phrase (ES) max: 500',
            'expectativa_ES.required' => 'Expectation (ES) required',
            'expectativa_ES.max' => 'Expectation (ES) max: 500',
        ];
    }
}
